### ISSUE TITLE
Add good logo 

### ISSUE THREAD

**Issue by tarunyadav1** [tarunyadav1/Ecommerce-store-React-Redux-Firebase-StripePayment#1]
Make a better logo for this project.

**Comment by harjotscs** [comment]
I would like to work on this issue. Can I ??

**Comment by gennady9** [comment]
Solved in PR #2

**Comment by tarunyadav1** [comment]
Thanks  @gennady9

**Comment by gennady9** [comment]
> Thanks @gennady9

You're welcome 👍 
can you please add "hacktoberfest-accepted" label to this PR? :)

**Comment by tarunyadav1** [comment]
@gennady9  Please like the project
