### ISSUE TITLE
Payment gateway

### ISSUE THREAD

**Issue by sourabhz-7** [tarunyadav1/Ecommerce-store-React-Redux-Firebase-StripePayment#3]
Sir How can we add razorpay payment gateway pls help.
And your stripe payment in live demo is not working.

**Comment by tarunyadav1** [comment]
I need to update the stripe payment. 
I never work with razorpay.

**Comment by sourabhz-7** [comment]
Ok sir . But please if you ever work with razorpay try to integrate it as a payment gateway coz it gives many payment options inside it .

**Comment by tarunyadav1** [comment]
Okay @sourabhz-7
